export default {
  SF_BLACK: 'SF-Black',
  SF_BOLD: 'SF-Bold',
  SF_LIGHT: 'SF-Light',
  SF_ITALIC: 'SF-Italic',
  SF_REGULAR: 'SF-Regular',
  SF_THIN: 'SF-Thin',
  SF_BLACK: 'SF-Pro-Display-Black',
  SF_BOLD: 'SF-Pro-Display-Bold',
  SF_HEAVY: 'SF-Pro-Display-Heavy',
  SF_LIGHT: 'SF-Pro-Display-Light',
  SF_MEDIUM: 'SF-Pro-Display-Medium',
  SF_REGULAR: 'SF-Pro-Display-Regular',
  SF_SEMIBOLD: 'SF-Pro-Display-Semibold',
  SF_THIN: 'SF-Pro-Display-Thin',
  SF_ULTRALIGHT: 'SF-Pro-Display-Ultralight',
};
